name = "CgenPack"
author = "Alice"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52cfea27732f4ce1e9de3eb1569a9a36cf8fbd54e0b64636df8294a68ec34d37"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
