name = "CgenPack"
author = "Alice"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "53673e98d38a9fc91cfb56c707d29310f1e366876ba17c63b1ef752a0585fe34"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
