name = "CgenPack"
author = "Alice"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8e78cb3eef60951d148cead8049fb754488f0995addf55a8e0dc3d2a08c8f46"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
