name = "CgenPack"
author = "Alice"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cfc92437422236ba3bc0f3e9eead47fac73f5eecbd7c5f5f228907d6ac1331b3"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
